verbone = input("Give me a verb (action word) describing your favorite activity.")
verbtwo = input("Another verb, for something you wish you could do?")
verbthree = input("One more, for your least favorite extracurricular.")
noun = input("Your least favorite imaginary place?")
num = input("The age that you think you'll live up to?")
celeb = input("Now, your favorite celebrity.")

print(f"When you were {verbone} past the houses in your neighborhood, you came across a peculiar sight.")
print(f"For some reason, {num} people were all {verbtwo} around an area.")
print(f"{verbthree} your way over there, you notice that {celeb} is there.")
print(f"{celeb} is inviting everyone to to to {noun} with them, free of charge.")
print(f"You refuse, for nothing could convince you to go. No one cares. The end.")