verbone = input("Give me a verb (action word).")
verbtwo = input("Another verb?")
verbthree = input("One more.")
noun = input("Now one noun (person, place, or thing)")
num = input("A number?")
celeb = input("Now a celebrity guest.")
